In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('song_data.csv')

In [4]:
df.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [5]:
triplets_df = pd.read_table('triplets_file.txt',header=None)
triplets_df.columns = ['user_id', 'song_id', 'listen_count']
triplets_df.head()

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

Recommendation System

In [6]:
df= pd.merge(triplets_df, df.drop_duplicates(['song_id']), on="song_id", how="left").head(10000)
df

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999
...,...,...,...,...,...,...,...
9995,15cc706a7f24975ca831aaaf297bf0392746b3fe,SOFSETB12A8C134038,2,Show Me How To Live,Audioslave,Audioslave,2002
9996,15cc706a7f24975ca831aaaf297bf0392746b3fe,SOHIROU12AB01852AF,5,Billy Liar,Billy Liar (CD-Single),The Decemberists,2003
9997,15cc706a7f24975ca831aaaf297bf0392746b3fe,SOOAVGC12AB01821EC,5,The Bachelor and the Bride,Her Majesty The Decemberists,The Decemberists,2003
9998,15cc706a7f24975ca831aaaf297bf0392746b3fe,SOPKEIV12AB018220D,5,Red Right Ankle,Her Majesty The Decemberists,The Decemberists,2003
9999,15cc706a7f24975ca831aaaf297bf0392746b3fe,SOQSUMQ12AB01821F7,5,Song for Myla Goldberg,Her Majesty The Decemberists,The Decemberists,2003

In [7]:
song = df.groupby(['title']).agg({'listen_count': 'count'}).reset_index()
song_sum = song['listen_count'].sum()
song['percentage']  = song['listen_count'].div(song_sum)*100
song.sort_values(['listen_count', 'title'], ascending = [0,1])

                               title  listen_count  percentage
3576                   Sehr kosmisch            45        0.45
4995                  You're The One            36        0.36
4577                            Undo            32        0.32
1044  Dog Days Are Over (Radio Edit)            28        0.28
3571                         Secrets            28        0.28
...                              ...           ...         ...
5026                      high fives             1        0.01
5027                  in white rooms             1        0.01
5030                paranoid android             1        0.01
5036          ¿Lo Ves? [Piano Y Voz]             1        0.01
5037                           Época             1        0.01

[5038 rows x 3 columns]

In [8]:
users = df['user_id'].unique()
len(users)

365

In [9]:
songs = song['title'].unique()
len(songs)

5038

In [10]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(df,test_size=0.30, random_state=101)

In [23]:
class item_similarity_recommender_py():
    def __init__(self):
        self.train_data = None
        self.user_id = None
        self.item_id = None
        self.cooccurence_matrix = None
        self.songs_dict = None
        self.rev_songs_dict = None
        self.item_similarity_recommendations = None
        
    def get_user_items(self, user):
        user_data = self.train_data[self.train_data[self.user_id] == user]
        user_items = list(user_data[self.item_id].unique())
        
        return user_items
        
    def get_item_users(self, item):
        item_data = self.train_data[self.train_data[self.item_id] == item]
        item_users = set(item_data[self.user_id].unique())
            
        return item_users
        
    def get_all_items_train_data(self):
        all_items = list(self.train_data[self.item_id].unique())
            
        return all_items
        
    def construct_cooccurence_matrix(self, user_songs, all_songs):
            
        user_songs_users = []        
        for i in range(0, len(user_songs)):
            user_songs_users.append(self.get_item_users(user_songs[i]))
        cooccurence_matrix = np.matrix(np.zeros(shape=(len(user_songs), len(all_songs))), float)
           

        for i in range(0,len(all_songs)):
            songs_i_data = self.train_data[self.train_data[self.item_id] == all_songs[i]]
            users_i = set(songs_i_data[self.user_id].unique())
            
            for j in range(0,len(user_songs)):       
                users_j = user_songs_users[j]
                users_intersection = users_i.intersection(users_j)
                if len(users_intersection) != 0:
                    users_union = users_i.union(users_j)
                    cooccurence_matrix[j,i] = float(len(users_intersection))/float(len(users_union))
                else:
                    cooccurence_matrix[j,i] = 0
                    
        
        return cooccurence_matrix

    
    def generate_top_recommendations(self, user, cooccurence_matrix, all_songs, user_songs):
        print("Non zero values in cooccurence_matrix :%d" % np.count_nonzero(cooccurence_matrix))
        
        user_sim_scores = cooccurence_matrix.sum(axis=0)/float(cooccurence_matrix.shape[0])
        user_sim_scores = np.array(user_sim_scores)[0].tolist()
 
        sort_index = sorted(((e,i) for i,e in enumerate(list(user_sim_scores))), reverse=True)
    
        columns = ['user_id', 'song', 'score', 'rank']
        df = pd.DataFrame(columns=columns)
         
        rank = 1 
        for i in range(0,len(sort_index)):
            if ~np.isnan(sort_index[i][0]) and all_songs[sort_index[i][1]] not in user_songs and rank <= 10:
                df.loc[len(df)]=[user,all_songs[sort_index[i][1]],sort_index[i][0],rank]
                rank = rank+1
        if df.shape[0] == 0:
            print("The current user has no songs for training the item similarity based recommendation model.")
            return -1
        else:
            return df
 
    def create(self, train_data, user_id, item_id):
        self.train_data = train_data
        self.user_id = user_id
        self.item_id = item_id

    def recommend(self, user):
        
        user_songs = self.get_user_items(user)    
            
        print("No. of unique songs for the user: %d" % len(user_songs))
        all_songs = self.get_all_items_train_data()
        
        print("no. of unique songs in the training set: %d" % len(all_songs))
        cooccurence_matrix = self.construct_cooccurence_matrix(user_songs, all_songs)
        df_recommendations = self.generate_top_recommendations(user, cooccurence_matrix, all_songs, user_songs)
        return df_recommendations
    
    def get_similar_items(self, item_list):
        user_songs = item_list
        all_songs = self.get_all_items_train_data()
        print("no. of unique songs in the training set: %d" % len(all_songs))
        cooccurence_matrix = self.construct_cooccurence_matrix(user_songs, all_songs)
        user = ""
        df_recommendations = self.generate_top_recommendations(user, cooccurence_matrix, all_songs, user_songs)
        return df_recommendations

In [24]:
model = item_similarity_recommender_py()

In [25]:
model.create(train,'user_id' , 'title')

In [26]:
user_id = users[5]
user_items = model.get_user_items(user_id)
for user_item in user_items:
    print(user_item)
model.recommend(user_id)

The Real Slim Shady
Ghosts 'n' Stuff (Original Instrumental Mix)
Missing You
Without Me
16 Candles
Somebody To Love
No. of unique songs for the user: 6
no. of unique songs in the training set: 4040
Non zero values in cooccurence_matrix :1304

,user_id,song,score,rank
0,4bd88bfb25263a75bbdd467e74018f4ae570e5df,American Idiot [feat. Green Day & The Cast Of ...,0.167105,1
1,4bd88bfb25263a75bbdd467e74018f4ae570e5df,The Middle,0.108243,2
2,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Civil War,0.107143,3
3,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Don't Cry (Original),0.107143,4
4,4bd88bfb25263a75bbdd467e74018f4ae570e5df,That Should Be Me,0.105489,5
5,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Love Me,0.101208,6
6,4bd88bfb25263a75bbdd467e74018f4ae570e5df,One Less Lonely Girl,0.100280,7
7,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Superman,0.096296,8
8,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Afterlife (Album Version),0.090476,9
9,4bd88bfb25263a75bbdd467e74018f4ae570e5df,Mockingbird,0.090061,10